-- TravelOrder
-- CREATE SEQUENCE IF NOT EXISTS travelorder_sequence START WITH 1 INCREMENT BY 1;
-- INSERT INTO TravelOrder(id)
-- VALUES (nextval('travelorder_sequence')),
--     (nextval('travelorder_sequence')),
--     (nextval('travelorder_sequence')),
--     (nextval('travelorder_sequence')),
--     (nextval('travelorder_sequence'));